//! Dart/Flutter schema generation from a contract snapshot.

use std::{collections::HashSet, fmt::Write, path::Path};

use kalamdb_sql::contracts::{
    ContractField, ContractSnapshot, ContractTable, ContractTableKind, ContractTypeKind,
};

use crate::{
    error::{CLIError, Result},
    workflow::schema::{
        naming::{camel_case, contract_hash_line, value_ident, AssignedNames, DEFAULT_SCHEMA},
        types::{render_field_type, TargetLang},
    },
};

const GENERATED_HEADER: &str = "// Generated by kalam schema gen. Do not edit.\n// Row codecs and \
                                KalamTableSpec values for kalam_sync.\n// Action queues stay with \
                                kalam_sync_generator / build_runner.\n";

pub fn write_dart_schema(
    output_path: &Path,
    snapshot: &ContractSnapshot,
    hash: &str,
    names: &AssignedNames,
) -> Result<()> {
    if let Some(parent) = output_path.parent() {
        std::fs::create_dir_all(parent).map_err(|error| {
            CLIError::FileError(format!("failed to create '{}': {error}", parent.display()))
        })?;
    }
    let source = generate_dart_source(snapshot, hash, names);
    std::fs::write(output_path, source).map_err(|error| {
        CLIError::FileError(format!("failed to write '{}': {error}", output_path.display()))
    })?;
    Ok(())
}

pub fn generate_dart_source(
    snapshot: &ContractSnapshot,
    hash: &str,
    names: &AssignedNames,
) -> String {
    let mut out = String::new();
    out.push_str(GENERATED_HEADER);
    out.push_str("// ");
    out.push_str(&contract_hash_line(hash));
    out.push_str("\nimport 'package:kalam_sync/kalam_sync.dart';\n\n");

    for (id, ty) in &snapshot.types {
        match &ty.kind {
            ContractTypeKind::Enum { labels } => {
                let ident = names.type_ident(id);
                let _ = writeln!(out, "enum {ident} {{");
                for (index, label) in labels.iter().enumerate() {
                    let comma = if index + 1 == labels.len() { ";" } else { "," };
                    let _ = writeln!(out, "  {}('{label}'){comma}", camel_case(label));
                }
                let _ = writeln!(out, "  const {ident}(this.wire);\n  final String wire;\n}}\n");
            },
            ContractTypeKind::Composite { fields } => {
                write_row_class(&mut out, names.type_ident(id), fields, names, snapshot);
            },
            ContractTypeKind::ImplicitTableRow { .. } | ContractTypeKind::RowAlias { .. } => {},
        }
    }

    for table in snapshot.tables.values() {
        let canonical_id = table
            .row_alias_id
            .as_ref()
            .map(|id| id.as_str().to_string())
            .unwrap_or_else(|| table.row_type_id.as_str().to_string());
        write_row_class(&mut out, names.type_ident(&canonical_id), &table.fields, names, snapshot);
        if let Some(alias) = &table.row_alias_id {
            let alias_ident = names.type_ident(alias.as_str());
            let row_ident = names.type_ident(table.row_type_id.as_str());
            if alias_ident != row_ident {
                let _ = writeln!(out, "typedef {row_ident} = {alias_ident};\n");
            }
        }
    }

    out.push_str("abstract final class KalamTables {\n  KalamTables._();\n");
    if snapshot.tables.is_empty() {
        out.push_str("}\n");
        return out;
    }
    out.push('\n');
    let mut used_const_names = HashSet::new();
    for table in snapshot.tables.values() {
        let class_name = canonical_table_class(table, names);
        let const_name =
            unique_ident(value_ident(&table.schema, &table.name, false), &mut used_const_names);
        write_spec(&mut out, table, &class_name, &const_name);
        out.push('\n');
    }
    out.push_str("}\n\n");
    out.push_str(DART_HELPERS);
    out
}

fn canonical_table_class(table: &ContractTable, names: &AssignedNames) -> String {
    let canonical_id = table
        .row_alias_id
        .as_ref()
        .map(|id| id.as_str().to_string())
        .unwrap_or_else(|| table.row_type_id.as_str().to_string());
    names.type_ident(&canonical_id).to_string()
}

fn write_row_class(
    out: &mut String,
    class_name: &str,
    fields: &[ContractField],
    names: &AssignedNames,
    snapshot: &ContractSnapshot,
) {
    let columns: Vec<DartColumn> = fields
        .iter()
        .map(|field| DartColumn::from_field(field, names, snapshot))
        .collect();
    let _ = writeln!(out, "final class {class_name} {{");
    out.push_str("  const ");
    out.push_str(class_name);
    out.push_str("({\n");
    for column in &columns {
        if column.nullable {
            let _ = writeln!(out, "    this.{},", column.field_name);
        } else {
            let _ = writeln!(out, "    required this.{},", column.field_name);
        }
    }
    out.push_str("  });\n\n");

    for column in &columns {
        let _ = writeln!(out, "  final {} {};", column.dart_type, column.field_name);
    }

    out.push_str("\n  String get kalamRowKey => ");
    match columns.iter().find(|column| column.is_key).or_else(|| columns.first()) {
        Some(key) if key.base_type == "int" || key.base_type == "String" => {
            if key.nullable {
                let _ = write!(out, "{}.toString()", key.field_name);
            } else if key.base_type == "String" {
                out.push_str(&key.field_name);
            } else {
                let _ = write!(out, "{}.toString()", key.field_name);
            }
        },
        Some(key) => {
            let _ = write!(out, "{}.toString()", key.field_name);
        },
        None => out.push_str("''"),
    }
    out.push_str(";\n\n");

    out.push_str("  Map<String, Object?> toJson() => {\n");
    for column in &columns {
        let _ = writeln!(out, "        '{}': {},", column.sql_name, column.encode());
    }
    out.push_str("      };\n\n");

    let _ = writeln!(
        out,
        "  factory {class_name}.fromJson(Map<String, Object?> json) => {class_name}("
    );
    for column in &columns {
        let _ = writeln!(out, "        {}: {},", column.field_name, column.decode());
    }
    out.push_str("      );\n}\n\n");
}

fn write_spec(out: &mut String, table: &ContractTable, class_name: &str, const_name: &str) {
    let _ = writeln!(out, "  static final {const_name} = KalamTableSpec<{class_name}>(");
    let _ = writeln!(out, "    tableId: '{}',", escape_dart_string(&wire_table_id(table)));
    let _ =
        writeln!(out, "    keyColumn: '{}',", escape_dart_string(&key_column_name(&table.fields)));
    let _ = writeln!(out, "    mode: KalamSyncMode.{},", sync_mode(table.kind));
    out.push_str("    keyOf: (row) => row.kalamRowKey,\n");
    out.push_str("    encode: (row) => row.toJson(),\n");
    let _ = writeln!(out, "    decode: {class_name}.fromJson,");
    out.push_str("  );\n");
}

fn wire_table_id(table: &ContractTable) -> String {
    if table.schema.eq_ignore_ascii_case(DEFAULT_SCHEMA) {
        table.name.clone()
    } else {
        table.table_id.clone()
    }
}

fn key_column_name(fields: &[ContractField]) -> String {
    fields
        .iter()
        .find(|field| field.name.eq_ignore_ascii_case("id"))
        .or_else(|| fields.first())
        .map(|field| field.name.clone())
        .unwrap_or_else(|| "id".to_string())
}

fn sync_mode(kind: ContractTableKind) -> &'static str {
    match kind {
        ContractTableKind::Stream => "replicaOnly",
        ContractTableKind::Unspecified | ContractTableKind::User | ContractTableKind::Shared => {
            "bidirectional"
        },
    }
}

struct DartColumn {
    sql_name:   String,
    field_name: String,
    dart_type:  String,
    base_type:  String,
    nullable:   bool,
    is_key:     bool,
    named_type: Option<String>,
    is_enum:    bool,
}

impl DartColumn {
    fn from_field(
        field: &ContractField,
        names: &AssignedNames,
        snapshot: &ContractSnapshot,
    ) -> Self {
        let dart_type = render_field_type(field, names, TargetLang::Dart);
        let is_enum = field
            .type_id
            .as_ref()
            .and_then(|id| snapshot.types.get(id.as_str()))
            .is_some_and(|ty| matches!(ty.kind, ContractTypeKind::Enum { .. }));
        let base_type = if field.type_id.is_some() {
            names.type_ident(field.type_id.as_ref().unwrap().as_str()).to_string()
        } else {
            crate::workflow::schema::types::builtin(&field.type_name, TargetLang::Dart).to_string()
        };
        Self {
            sql_name: field.name.clone(),
            field_name: dart_field_name(&field.name),
            dart_type,
            named_type: field.type_id.as_ref().map(|id| names.type_ident(id.as_str()).to_string()),
            is_enum,
            nullable: !field.not_null,
            is_key: field.name.eq_ignore_ascii_case("id"),
            base_type,
        }
    }

    fn encode(&self) -> String {
        let name = &self.field_name;
        if self.named_type.is_some() {
            if self.is_enum {
                return if self.nullable {
                    format!("{name}?.wire")
                } else {
                    format!("{name}.wire")
                };
            }
            return if self.nullable {
                format!("{name}?.toJson()")
            } else {
                format!("{name}.toJson()")
            };
        }
        match (self.base_type.as_str(), self.nullable) {
            ("DateTime", true) => format!("{name}?.toIso8601String()"),
            ("DateTime", false) => format!("{name}.toIso8601String()"),
            _ => name.to_string(),
        }
    }

    fn decode(&self) -> String {
        let json = format!("json['{}']", escape_dart_string(&self.sql_name));
        if let Some(named) = &self.named_type {
            if self.is_enum {
                return if self.nullable {
                    format!(
                        "{json} == null ? null : {named}.values.firstWhere((value) => value.wire \
                         == _asString({json}))"
                    )
                } else {
                    format!("{named}.values.firstWhere((value) => value.wire == _asString({json}))")
                };
            }
            return if self.nullable {
                format!("{json} == null ? null : {named}.fromJson(_asJsonMap({json}))")
            } else {
                format!("{named}.fromJson(_asJsonMap({json}))")
            };
        }
        match (self.base_type.as_str(), self.nullable) {
            ("int", false) => format!("_asInt({json})"),
            ("int", true) => format!("_asIntOrNull({json})"),
            ("double", false) => format!("_asDouble({json})"),
            ("double", true) => format!("_asDoubleOrNull({json})"),
            ("bool", false) => format!("_asBool({json})"),
            ("bool", true) => format!("_asBoolOrNull({json})"),
            ("DateTime", false) => format!("_asDateTime({json})"),
            ("DateTime", true) => format!("_asDateTimeOrNull({json})"),
            ("Map<String, Object?>", false) => format!("_asJsonMap({json})"),
            ("Map<String, Object?>", true) => format!("_asJsonMapOrNull({json})"),
            ("List<double>", false) => format!("_asDoubleList({json})"),
            ("List<double>", true) => format!("_asDoubleListOrNull({json})"),
            (_, false) => format!("_asString({json})"),
            (_, true) => format!("_asStringOrNull({json})"),
        }
    }
}

fn dart_field_name(sql_name: &str) -> String {
    sanitize_ident(&camel_case(sql_name))
}

fn sanitize_ident(value: &str) -> String {
    let mut ident: String = value
        .chars()
        .map(|ch| {
            if ch.is_ascii_alphanumeric() || ch == '_' {
                ch
            } else {
                '_'
            }
        })
        .collect();
    if ident.is_empty() || ident.chars().next().is_some_and(|ch| ch.is_ascii_digit()) {
        ident.insert(0, 'n');
    }
    if DART_KEYWORDS.contains(&ident.as_str()) {
        ident.push('_');
    }
    ident
}

fn unique_ident(base: String, used: &mut HashSet<String>) -> String {
    if used.insert(base.clone()) {
        return base;
    }
    let mut index = 2u32;
    loop {
        let candidate = format!("{base}{index}");
        if used.insert(candidate.clone()) {
            return candidate;
        }
        index += 1;
    }
}

fn escape_dart_string(value: &str) -> String {
    value.replace('\\', "\\\\").replace('\'', "\\'")
}

const DART_KEYWORDS: &[&str] = &[
    "assert", "break", "case", "catch", "class", "const", "continue", "default", "do", "else",
    "enum", "extends", "false", "final", "finally", "for", "if", "in", "is", "new", "null",
    "rethrow", "return", "super", "switch", "this", "throw", "true", "try", "var", "void", "while",
    "with", "yield",
];

const DART_HELPERS: &str = r#"int _asInt(Object? value) {
  if (value is int) return value;
  if (value is num) return value.toInt();
  if (value is String) return int.parse(value);
  throw FormatException('expected int, got $value');
}

int? _asIntOrNull(Object? value) => value == null ? null : _asInt(value);

double _asDouble(Object? value) {
  if (value is double) return value;
  if (value is num) return value.toDouble();
  if (value is String) return double.parse(value);
  throw FormatException('expected double, got $value');
}

double? _asDoubleOrNull(Object? value) => value == null ? null : _asDouble(value);

bool _asBool(Object? value) {
  if (value is bool) return value;
  if (value is num) return value != 0;
  if (value is String) {
    switch (value.toLowerCase()) {
      case 'true':
      case '1':
        return true;
      case 'false':
      case '0':
        return false;
    }
  }
  throw FormatException('expected bool, got $value');
}

bool? _asBoolOrNull(Object? value) => value == null ? null : _asBool(value);

DateTime _asDateTime(Object? value) {
  if (value is DateTime) return value;
  if (value is String) return DateTime.parse(value);
  if (value is int) return DateTime.fromMillisecondsSinceEpoch(value, isUtc: true);
  throw FormatException('expected DateTime, got $value');
}

DateTime? _asDateTimeOrNull(Object? value) =>
    value == null ? null : _asDateTime(value);

String _asString(Object? value) {
  if (value is String) return value;
  if (value == null) throw FormatException('expected String, got null');
  return value.toString();
}

String? _asStringOrNull(Object? value) => value == null ? null : _asString(value);

Map<String, Object?> _asJsonMap(Object? value) {
  if (value is Map<String, Object?>) return value;
  if (value is Map) {
    return value.map((key, nested) => MapEntry(key.toString(), nested));
  }
  throw FormatException('expected JSON object, got $value');
}

Map<String, Object?>? _asJsonMapOrNull(Object? value) =>
    value == null ? null : _asJsonMap(value);

List<double> _asDoubleList(Object? value) {
  if (value is List<double>) return value;
  if (value is List) {
    return value.map(_asDouble).toList();
  }
  throw FormatException('expected List<double>, got $value');
}

List<double>? _asDoubleListOrNull(Object? value) =>
    value == null ? null : _asDoubleList(value);
"#;

#[cfg(test)]
mod tests {
    use kalamdb_sql::compile_contract_sql;

    use super::*;
    use crate::workflow::schema::naming::{assign_names, NamingOptions};

    #[test]
    fn generates_table_specs_and_row_codecs_from_sql() {
        let snapshot = compile_contract_sql(
            r#"
CREATE TABLE users (
  id INTEGER PRIMARY KEY,
  email TEXT NOT NULL,
  created_at TIMESTAMP
);
"#,
            "public",
        )
        .unwrap();
        let hash = kalamdb_sql::canonical_contract_hash(&snapshot);
        let names = assign_names(
            &snapshot,
            NamingOptions {
                unqualified_names: false,
            },
        )
        .unwrap();
        let source = generate_dart_source(&snapshot, &hash, &names);
        assert!(source.contains("Generated by kalam schema gen"));
        assert!(source.contains(&format!("contract_hash: {hash}")));
        assert!(!source.to_lowercase().contains("placeholder"));
        assert!(source.contains("import 'package:kalam_sync/kalam_sync.dart';"));
        assert!(source.contains("final class Users {"));
        assert!(source.contains("required this.id"));
        assert!(source.contains("required this.email"));
        assert!(source.contains("this.createdAt"));
        assert!(source.contains("factory Users.fromJson"));
        assert!(source.contains("static final users = KalamTableSpec<Users>("));
        assert!(source.contains("tableId: 'users'"));
        assert!(source.contains("keyColumn: 'id'"));
        assert!(source.contains("mode: KalamSyncMode.bidirectional"));
        assert!(source.contains("keyOf: (row) => row.kalamRowKey"));
        assert!(source.contains("encode: (row) => row.toJson()"));
        assert!(source.contains("decode: Users.fromJson"));
    }

    #[test]
    fn stream_tables_use_replica_only_mode() {
        let snapshot = compile_contract_sql(
            r#"
CREATE STREAM TABLE app.message_events (
  id TEXT PRIMARY KEY,
  payload JSON
);
"#,
            "public",
        )
        .unwrap();
        let hash = kalamdb_sql::canonical_contract_hash(&snapshot);
        let names = assign_names(
            &snapshot,
            NamingOptions {
                unqualified_names: false,
            },
        )
        .unwrap();
        let source = generate_dart_source(&snapshot, &hash, &names);
        assert!(source.contains("tableId: 'app.message_events'"));
        assert!(source.contains("final class AppMessageEvents {"));
        assert!(
            source.contains("static final appMessageEvents = KalamTableSpec<AppMessageEvents>(")
        );
        assert!(source.contains("mode: KalamSyncMode.replicaOnly"));
        assert!(source.contains("Map<String, Object?>? payload"));
    }

    #[test]
    fn nested_struct_and_alias_share_one_shape() {
        let snapshot = compile_contract_sql(
            r#"
CREATE SCHEMA chat;
CREATE TYPE chat.address AS (city TEXT, country TEXT);
CREATE TABLE chat.users (
  id BIGINT PRIMARY KEY,
  address chat.address,
  nickname TEXT
) ROW TYPE chat.user;
"#,
            "public",
        )
        .unwrap();
        let hash = kalamdb_sql::canonical_contract_hash(&snapshot);
        let names = assign_names(
            &snapshot,
            NamingOptions {
                unqualified_names: false,
            },
        )
        .unwrap();
        let source = generate_dart_source(&snapshot, &hash, &names);
        assert!(source.contains("final class ChatAddress {"));
        assert!(source.contains("final class ChatUser {"));
        assert!(source.contains("typedef ChatUsers = ChatUser;"));
        assert!(source.contains("ChatAddress? address"));
        assert!(source.contains("String? nickname"));
        assert!(source.contains("ChatAddress.fromJson"));
        assert!(!source.contains("final class ChatUsers {"));
    }

    #[test]
    fn empty_schema_emits_compilable_kalam_tables() {
        let snapshot = compile_contract_sql("-- no tables yet\n", "public").unwrap();
        let hash = kalamdb_sql::canonical_contract_hash(&snapshot);
        let names = assign_names(
            &snapshot,
            NamingOptions {
                unqualified_names: false,
            },
        )
        .unwrap();
        let source = generate_dart_source(&snapshot, &hash, &names);
        assert!(source.contains("abstract final class KalamTables"));
        assert!(!source.contains("KalamTableSpec<"));
        assert!(!source.contains("static final"));
    }

    #[test]
    fn write_dart_schema_creates_parent_directories() {
        let temp = tempfile::TempDir::new().unwrap();
        let output = temp.path().join("lib/generated/kalam.dart");
        let snapshot = compile_contract_sql(
            "CREATE TABLE todos (id TEXT PRIMARY KEY, title TEXT NOT NULL, done BOOLEAN NOT NULL);",
            "public",
        )
        .unwrap();
        let hash = kalamdb_sql::canonical_contract_hash(&snapshot);
        let names = assign_names(
            &snapshot,
            NamingOptions {
                unqualified_names: false,
            },
        )
        .unwrap();
        write_dart_schema(&output, &snapshot, &hash, &names).unwrap();
        let source = std::fs::read_to_string(&output).unwrap();
        assert!(source.contains("KalamTableSpec<Todos>"));
        assert!(source.contains("bool done"));
    }
}
