//! TypeScript client, server contracts, and one-shot procedure scaffolds.

use std::{
    collections::BTreeMap,
    fs,
    path::{Path, PathBuf},
};

use kalamdb_sql::contracts::{
    ContractField, ContractRoutine, ContractSnapshot, ContractTable, ContractTableKind,
    ContractTypeKind,
};

use crate::{
    error::{CLIError, Result},
    workflow::schema::{
        naming::{
            contract_hash_line, method_ident, schema_object_ident, value_ident, AssignedNames,
        },
        types::{render_field_type, TargetLang},
    },
};

const FUNCTIONS_DIR: &str = "functions";
const GENERATED_HEADER: &str = "// Generated by kalam schema gen. Do not edit.";

pub fn write_typescript(
    output_path: &Path,
    snapshot: &ContractSnapshot,
    hash: &str,
    names: &AssignedNames,
    project_root: &Path,
) -> Result<()> {
    write_text(output_path, &generate_client_source(snapshot, hash, names))?;
    write_procedure_artifacts(project_root, snapshot, hash, names)?;
    Ok(())
}

pub fn generate_client_source(
    snapshot: &ContractSnapshot,
    hash: &str,
    names: &AssignedNames,
) -> String {
    let mut out = String::new();
    out.push_str(GENERATED_HEADER);
    out.push('\n');
    out.push_str("// ");
    out.push_str(&contract_hash_line(hash));
    out.push_str("\n\n");

    let needs_orm = !snapshot.tables.is_empty();
    if needs_orm {
        out.push_str("import { kTable } from '@kalamdb/orm';\n");
        out.push_str(
            "import { integer, text, timestamp, boolean, jsonb, bigint } from \
             'drizzle-orm/pg-core';\n\n",
        );
    }

    out.push_str(
        "export type JsonValue = string | number | boolean | null | JsonValue[] | { [key: \
         string]: JsonValue };\n\n",
    );
    emit_shared_types(&mut out, snapshot, names, "export ");
    emit_ktables(&mut out, snapshot);
    emit_frontend_client(&mut out, snapshot, names);
    out
}

pub fn generate_contracts_source(
    snapshot: &ContractSnapshot,
    hash: &str,
    names: &AssignedNames,
) -> String {
    let mut out = String::new();
    out.push_str(GENERATED_HEADER);
    out.push('\n');
    out.push_str("// ");
    out.push_str(&contract_hash_line(hash));
    out.push_str("\n\n");
    out.push_str(
        "export type JsonValue = string | number | boolean | null | JsonValue[] | { [key: \
         string]: JsonValue };\n\n",
    );
    emit_shared_types(&mut out, snapshot, names, "export ");
    out.push_str(
        "export function defineProcedure<C extends { input: unknown; output: unknown }>(\n",
    );
    out.push_str(
        "  handler: (ctx: unknown, input: C[\"input\"]) => Promise<C[\"output\"]> | \
         C[\"output\"],\n",
    );
    out.push_str(") {\n  return handler;\n}\n");
    out
}

fn emit_shared_types(
    out: &mut String,
    snapshot: &ContractSnapshot,
    names: &AssignedNames,
    export: &str,
) {
    for (id, ty) in &snapshot.types {
        match &ty.kind {
            ContractTypeKind::Enum { labels } => {
                let ident = names.type_ident(id);
                let union = labels
                    .iter()
                    .map(|label| format!("\"{}\"", escape_ts_string(label)))
                    .collect::<Vec<_>>()
                    .join(" | ");
                let _ = writeln_str(out, &format!("{export}type {ident} = {union};\n"));
            },
            ContractTypeKind::Composite { fields } => {
                emit_object_type(out, export, names.type_ident(id), fields, names);
            },
            ContractTypeKind::ImplicitTableRow { .. } | ContractTypeKind::RowAlias { .. } => {},
        }
    }

    for table in snapshot.tables.values() {
        let canonical_id = table
            .row_alias_id
            .as_ref()
            .map(|id| id.as_str().to_string())
            .unwrap_or_else(|| table.row_type_id.as_str().to_string());
        emit_object_type(out, export, names.type_ident(&canonical_id), &table.fields, names);
        if let Some(alias) = &table.row_alias_id {
            let alias_ident = names.type_ident(alias.as_str());
            let row_ident = names.type_ident(table.row_type_id.as_str());
            if alias_ident != row_ident {
                let _ = writeln_str(out, &format!("{export}type {row_ident} = {alias_ident};\n"));
            }
        }
    }

    for (id, routine) in &snapshot.routines {
        emit_procedure_type(out, export, names.routine_ident(id), routine, names);
    }
}

fn emit_object_type(
    out: &mut String,
    export: &str,
    ident: &str,
    fields: &[ContractField],
    names: &AssignedNames,
) {
    out.push_str(export);
    out.push_str("type ");
    out.push_str(ident);
    out.push_str(" = {\n");
    for field in fields {
        let ty = render_field_type(field, names, TargetLang::TypeScript);
        out.push_str("  ");
        out.push_str(&field.name);
        out.push_str(": ");
        out.push_str(&ty);
        out.push_str(";\n");
    }
    out.push_str("};\n\n");
}

fn emit_procedure_type(
    out: &mut String,
    export: &str,
    ident: &str,
    routine: &ContractRoutine,
    names: &AssignedNames,
) {
    out.push_str(export);
    out.push_str("type ");
    out.push_str(ident);
    out.push_str(" = {\n  input: {\n");
    for field in &routine.parameters {
        let ty = render_field_type(field, names, TargetLang::TypeScript);
        out.push_str("    ");
        out.push_str(&field.name);
        out.push_str(": ");
        out.push_str(&ty);
        out.push_str(";\n");
    }
    out.push_str("  };\n  output: ");
    match &routine.return_type {
        Some(ret) => out.push_str(&render_field_type(ret, names, TargetLang::TypeScript)),
        None => out.push_str("void"),
    }
    out.push_str(";\n};\n\n");
}

fn emit_ktables(out: &mut String, snapshot: &ContractSnapshot) {
    for table in snapshot.tables.values() {
        let var_name = value_ident(&table.schema, &table.name, false);
        let table_name = wire_table_name(table);
        let factory = match table.kind {
            ContractTableKind::User => "kTable.user",
            ContractTableKind::Shared => "kTable.shared",
            ContractTableKind::Stream => "kTable.stream",
            ContractTableKind::Unspecified => "kTable",
        };
        out.push_str("export const ");
        out.push_str(&var_name);
        out.push_str(" = ");
        out.push_str(factory);
        out.push_str("(");
        out.push_str(&format!("\"{}\"", escape_ts_string(&table_name)));
        out.push_str(", {\n");
        for field in &table.fields {
            out.push_str("  ");
            out.push_str(&field.name);
            out.push_str(": ");
            out.push_str(&drizzle_column(field));
            out.push_str(",\n");
        }
        out.push_str("});\n\n");
    }
}

fn drizzle_column(field: &ContractField) -> String {
    let mut expr = if field.type_id.is_some() {
        format!("jsonb(\"{}\")", escape_ts_string(&field.name))
    } else {
        let sql = field.type_name.to_ascii_uppercase();
        match sql.as_str() {
            "BOOLEAN" | "BOOL" => format!("boolean(\"{}\")", escape_ts_string(&field.name)),
            "INT" | "INTEGER" | "INT4" | "SERIAL" | "SMALLINT" | "INT2" => {
                format!("integer(\"{}\")", escape_ts_string(&field.name))
            },
            "BIGINT" | "INT8" | "INT64" | "BIGSERIAL" => {
                format!("bigint(\"{}\", {{ mode: \"bigint\" }})", escape_ts_string(&field.name))
            },
            "TIMESTAMP" | "TIMESTAMPTZ" | "DATETIME" => {
                format!("timestamp(\"{}\", {{ mode: \"date\" }})", escape_ts_string(&field.name))
            },
            "JSON" | "JSONB" | "FILE" => format!("jsonb(\"{}\")", escape_ts_string(&field.name)),
            _ => format!("text(\"{}\")", escape_ts_string(&field.name)),
        }
    };
    if field.name == "id" {
        expr.push_str(".primaryKey()");
    } else if field.not_null {
        expr.push_str(".notNull()");
    }
    expr
}

fn emit_frontend_client(out: &mut String, snapshot: &ContractSnapshot, names: &AssignedNames) {
    let mut by_schema: BTreeMap<&str, Vec<&ContractRoutine>> = BTreeMap::new();
    for routine in snapshot.routines.values() {
        by_schema.entry(routine.schema.as_str()).or_default().push(routine);
    }
    out.push_str("export const kalam = {\n");
    for (schema, routines) in &by_schema {
        out.push_str("  ");
        out.push_str(&schema_object_ident(schema));
        out.push_str(": {\n");
        for routine in routines {
            let method = method_ident(&routine.name);
            let ident = names.routine_ident(routine.routine_id.as_str());
            out.push_str("    ");
            out.push_str(&method);
            out.push_str(": async (input: ");
            out.push_str(ident);
            out.push_str("[\"input\"]): Promise<");
            out.push_str(ident);
            out.push_str("[\"output\"]> => {\n");
            out.push_str("      throw new Error(\"procedure client has no local runtime\");\n");
            out.push_str("    },\n");
        }
        out.push_str("  },\n");
    }
    out.push_str("};\n");
}

fn write_procedure_artifacts(
    project_root: &Path,
    snapshot: &ContractSnapshot,
    hash: &str,
    names: &AssignedNames,
) -> Result<()> {
    let ts_routines: Vec<&ContractRoutine> = snapshot
        .routines
        .values()
        .filter(|routine| is_typescript_routine(routine))
        .collect();
    if ts_routines.is_empty() && snapshot.routines.is_empty() {
        return Ok(());
    }

    let generated_dir = project_root.join(FUNCTIONS_DIR).join(".kalam").join("generated");
    write_text(
        &generated_dir.join("contracts.ts"),
        &generate_contracts_source(snapshot, hash, names),
    )?;
    write_text(
        &generated_dir.join("registry.ts"),
        &generate_registry_source(snapshot, hash, &ts_routines, names)?,
    )?;

    for routine in ts_routines {
        scaffold_procedure(project_root, routine, names)?;
    }
    Ok(())
}

fn generate_registry_source(
    snapshot: &ContractSnapshot,
    hash: &str,
    routines: &[&ContractRoutine],
    names: &AssignedNames,
) -> Result<String> {
    let _ = (snapshot, names);
    let mut out = String::new();
    out.push_str(GENERATED_HEADER);
    out.push('\n');
    out.push_str("// ");
    out.push_str(&contract_hash_line(hash));
    out.push_str("\n\n");
    for routine in routines {
        let import_name = value_ident(&routine.schema, &routine.name, false);
        let rel = format!("../../src/{}/{}", routine.schema, routine.name);
        out.push_str("import ");
        out.push_str(&import_name);
        out.push_str(" from \"");
        out.push_str(&rel);
        out.push_str("\";\n");
    }
    out.push_str("\nexport const procedures = {\n");
    for routine in routines {
        let import_name = value_ident(&routine.schema, &routine.name, false);
        out.push_str("  \"");
        out.push_str(routine.routine_id.as_str());
        out.push_str("\": ");
        out.push_str(&import_name);
        out.push_str(",\n");
    }
    out.push_str("};\n");
    Ok(out)
}

fn scaffold_procedure(
    project_root: &Path,
    routine: &ContractRoutine,
    names: &AssignedNames,
) -> Result<()> {
    let path = procedure_impl_path(project_root, routine);
    if path.exists() {
        let existing = fs::read_to_string(&path).map_err(|error| {
            CLIError::FileError(format!("failed to read '{}': {error}", path.display()))
        })?;
        if !existing.contains("export default") {
            return Err(CLIError::ConfigurationError(format!(
                "procedure implementation '{}' is missing `export default`; add `export default \
                 defineProcedure(...)` or delete the file to rescaffold",
                display_rel(project_root, &path)
            )));
        }
        return Ok(());
    }

    let ident = names.routine_ident(routine.routine_id.as_str());
    let source = format!(
        "import {{\n  defineProcedure,\n  type {ident},\n}} from \
         \"../../.kalam/generated/contracts\";\n\nexport default defineProcedure<{ident}>(\n  \
         async (ctx, input) => {{\n    throw new Error(\"not implemented\");\n  }},\n);\n"
    );
    write_text(&path, &source)
}

fn procedure_impl_path(project_root: &Path, routine: &ContractRoutine) -> PathBuf {
    project_root
        .join(FUNCTIONS_DIR)
        .join("src")
        .join(&routine.schema)
        .join(format!("{}.ts", routine.name))
}

fn is_typescript_routine(routine: &ContractRoutine) -> bool {
    match routine.language.as_deref() {
        None => true,
        Some(language) => matches!(
            language.to_ascii_uppercase().as_str(),
            "TS" | "TYPESCRIPT" | "JS" | "JAVASCRIPT" | "PLV8"
        ),
    }
}

fn wire_table_name(table: &ContractTable) -> String {
    if table.schema.eq_ignore_ascii_case("public") {
        table.name.clone()
    } else {
        table.table_id.clone()
    }
}

fn write_text(path: &Path, contents: &str) -> Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|error| {
            CLIError::FileError(format!("failed to create '{}': {error}", parent.display()))
        })?;
    }
    fs::write(path, contents).map_err(|error| {
        CLIError::FileError(format!("failed to write '{}': {error}", path.display()))
    })
}

fn display_rel(project_root: &Path, path: &Path) -> String {
    path.strip_prefix(project_root).unwrap_or(path).display().to_string()
}

fn escape_ts_string(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}

fn writeln_str(out: &mut String, value: &str) -> std::fmt::Result {
    out.push_str(value);
    if !value.ends_with('\n') {
        out.push('\n');
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use kalamdb_sql::compile_contract_sql;

    use super::*;
    use crate::workflow::schema::naming::{assign_names, NamingOptions};

    #[test]
    fn client_embeds_hash_nested_client_and_prefixed_types() {
        let snapshot = compile_contract_sql(GOLDEN_SQL, "public").unwrap();
        let hash = kalamdb_sql::canonical_contract_hash(&snapshot);
        let names = assign_names(
            &snapshot,
            NamingOptions {
                unqualified_names: false,
            },
        )
        .unwrap();
        let source = generate_client_source(&snapshot, &hash, &names);
        assert!(source.contains(&format!("contract_hash: {hash}")));
        assert!(source.contains("export type ChatAddress"));
        assert!(source.contains("address: ChatAddress | null"));
        assert!(source.contains("nickname: string | null"));
        assert!(source.contains("export type ChatUser"));
        assert!(source.contains("export type ChatUsers = ChatUser"));
        assert!(source.contains("export type ChatStatus = \"active\" | \"blocked\""));
        assert!(source.contains("kalam = {"));
        assert!(source.contains("chat: {"));
        assert!(source.contains("createMessage:"));
        assert!(source.contains("import { kTable } from '@kalamdb/orm'"));
        assert!(!source.contains("kalam.chat.createMessage"));
    }

    const GOLDEN_SQL: &str = r#"
CREATE SCHEMA chat;
CREATE TYPE chat.address AS (city TEXT, country TEXT);
CREATE TYPE chat.status AS ENUM ('active', 'blocked');
CREATE TABLE chat.users (
  id BIGINT PRIMARY KEY,
  email TEXT NOT NULL,
  address chat.address,
  nickname TEXT,
  status chat.status NOT NULL
) ROW TYPE chat.user;
CREATE PROCEDURE chat.create_message(user_id TEXT, body TEXT NOT NULL)
RETURNS chat.user
LANGUAGE TS;
"#;
}
